/**
 * @file version_info.h
 * @brief Generated version information header
 * @author XMD Build System
 * 
 * This file is automatically generated by CMake during the build process.
 * Do not edit this file directly.
 */

#ifndef XMD_VERSION_INFO_H
#define XMD_VERSION_INFO_H

#define XMD_VERSION_MAJOR 0
#define XMD_VERSION_MINOR 0
#define XMD_VERSION_PATCH 2
#define XMD_VERSION_STRING "0.0.2"
#define XMD_GIT_COMMIT "24f458a"
#define XMD_GIT_TAG "0.0.2"
#define XMD_GIT_BRANCH "modular-refactoring-20250801_184028"
#define XMD_BUILD_DATE "2025-08-02 02:54:28"
#define XMD_BUILD_TYPE "Debug"

#endif /* XMD_VERSION_INFO_H */
